// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn8eSJbz2Fl9Tr7yyqXqz763AmwwQGFeI',
    appId: '1:899752886466:web:7bd1865770bc3c25887b5b',
    messagingSenderId: '899752886466',
    projectId: 'scoot-rusl',
    authDomain: 'scoot-rusl.firebaseapp.com',
    storageBucket: 'scoot-rusl.firebasestorage.app',
    measurementId: 'G-DE6YXD9PX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoK96-u2URo8Z8ha8YCgEkD5pxhIU0Zrk',
    appId: '1:899752886466:android:778f0955bb6975ed887b5b',
    messagingSenderId: '899752886466',
    projectId: 'scoot-rusl',
    storageBucket: 'scoot-rusl.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn8eSJbz2Fl9Tr7yyqXqz763AmwwQGFeI',
    appId: '1:899752886466:web:3d97028265aa1a05887b5b',
    messagingSenderId: '899752886466',
    projectId: 'scoot-rusl',
    authDomain: 'scoot-rusl.firebaseapp.com',
    storageBucket: 'scoot-rusl.firebasestorage.app',
    measurementId: 'G-NWF8JY8P7E',
  );
}
